---
# build_site tasks file for otvl_service/otvl_web_v2/docker_build

- name: build_site display the site {{ current_site_item.name }} information
  debug:
    msg: "site item is {{ current_site_item }}"
  when: combined_otvl.debug

- name: Checkout the git project containing otvl_web v2 for {{ current_site_item.name }}
  git:
    repo: "{{ current_site_item.git.otvl_web.repo }}"
    dest: "{{ combined_otvl.config_paths.pkg }}/otvl_web/git/{{ current_site_item.name }}/otvl_web"
    version: "{{ current_site_item.git.otvl_web.version }}"
    update: true
    recursive: no
    force: yes
  register: otvl_web_git_checkout

- name: Checkout the git project containing the site for {{ current_site_item.name }}
  git:
    repo: "{{ current_site_item.git.otvl_site.repo }}"
    dest: "{{ combined_otvl.config_paths.pkg }}/otvl_web/git/{{ current_site_item.name }}/otvl_site"
    version: "{{ current_site_item.git.otvl_site.version }}"
    update: true
    recursive: no
    force: yes
  register: otvl_site_git_checkout

- name: Purge the otvl_web dir for site {{ current_site_item.name }}
  file:
    path: "{{ combined_otvl.config_paths.pkg }}/otvl_web/git/{{ current_site_item.name }}/otvl_site{{ current_site_item.git.otvl_site.site_build_dir }}/otvl_web"
    state: absent
  when: "otvl_site_git_checkout.changed or otvl_web_git_checkout.changed"
  register: otvl_site_git_checkout_purged

- name: Copy the otvl_web dir to the site {{ current_site_item.name }}
  ansible.builtin.copy:
    src: "{{ combined_otvl.config_paths.pkg }}/otvl_web/git/{{ current_site_item.name }}/otvl_web"
    remote_src: yes
    dest: "{{ combined_otvl.config_paths.pkg }}/otvl_web/git/{{ current_site_item.name }}/otvl_site{{ current_site_item.git.otvl_site.site_build_dir }}"
  register: otvl_site_git_updated

- name: Trigger build execution if site {{ current_site_item.name }} updated
  include_tasks: "otvl_service/base_service/tasks/remove_install_status_file.yml"
  vars:
    isf_name: "{{ current_site_item.name }}_built"
  when: otvl_site_git_updated.changed

- name: "Set the {{ current_site_item.name }} to be built the first time"
  include_tasks: "otvl_service/base_service/tasks/set_install_status_file.yml"
  vars:
    isf_name: "{{ current_site_item.name }}_built"
    isf_status: built
    isf_force: no

- name: Build the site {{ current_site_item.name }}

  block:
    - command:
        cmd: "docker login {{ combined_otvl.otvl_web_v2.docker_registry }} -u {{ combined_otvl.otvl_web_v2.docker_login }} --password-stdin"
        stdin: "{{ combined_otvl.otvl_web_v2.docker_password }}"
      register: docker_login
    - debug: var=docker_login.cmd
    - debug: var=docker_login.stderr_lines
    - debug: var=docker_login.stdout_lines

    - command:
        cmd: docker-compose build --pull
        chdir: "{{ combined_otvl.config_paths.pkg }}/otvl_web/git/{{ current_site_item.name }}/otvl_site{{ current_site_item.git.otvl_site.site_build_dir }}"
      environment:
        OTVL_WEB_REGISTRY: "{{ combined_otvl.otvl_web_v2.docker_registry }}"
      register: docker_compose_build
    - debug: var=docker_compose_build.cmd
    - debug: var=docker_compose_build.stderr_lines
    - debug: var=docker_compose_build.stdout_lines

    - command:
        cmd: docker-compose push
        chdir: "{{ combined_otvl.config_paths.pkg }}/otvl_web/git/{{ current_site_item.name }}/otvl_site{{ current_site_item.git.otvl_site.site_build_dir }}"
      environment:
        OTVL_WEB_REGISTRY: "{{ combined_otvl.otvl_web_v2.docker_registry }}"
      register: docker_compose_push
    - debug: var=docker_compose_push.cmd
    - debug: var=docker_compose_push.stderr_lines
    - debug: var=docker_compose_push.stdout_lines

  rescue:
  - name: "Site {{ current_site_item.name }} building failed, cancel build"
    include_tasks: "otvl_service/base_service/tasks/remove_install_status_file.yml"
    vars:
      isf_name: "{{ current_site_item.name }}_built"

  - name: "Site {{ current_site_item.name }} building failed, raise"
    fail:
      msg: "Site {{ current_site_item.name }} building failed, raise"

  when: set_isf.changed

###