---
# main tasks file for otvl_bastion/completed

- name: combine default with actual infra data
  set_fact:
    combined_infra: "{{ default_infra | combine(infra, recursive=True) }}"

- openstack.cloud.server_info:
    cloud: "{{ cloud_name }}"
    filters:
      metadata:
        hostname: "{{ combined_infra.security_groups.bastion_name }}"
  register: os_bastion_info

- name: Restrict security group rule SSH on {{ combined_infra.security_groups.cloud_init_access }} for cloud init access
  os_security_group_rule:
    cloud: "{{ cloud_name }}"
    security_group: "{{ combined_infra.security_groups.cloud_init_access }}"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
    state: absent

- name: Add security group rule SSH bastion only on {{ combined_infra.security_groups.cloud_init_access }} for cloud init access
  os_security_group_rule:
    cloud: "{{ cloud_name }}"
    security_group: "{{ combined_infra.security_groups.cloud_init_access }}"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: "{{ os_bastion_info.openstack_servers[0].public_v4 }}/0"

###
