---
# playbook file displaying ansible facts from openstack

- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: "Retreive facts about servers on openstack"
      os_server_facts:
        cloud: "{{ cloud_name }}"
        server: "*"
    
    - name: Show openstack servers
      debug:
        var: openstack_servers
    
    - name: Gather facts about previously created networks
      os_networks_facts:
        cloud: "{{ cloud_name }}"
      when: display_networks
    
    - name: Show openstack networks
      debug:
        var: openstack_networks
      when: display_networks
    
    - name: Gather facts about previously created subnetworks
      os_subnets_facts:
        cloud: "{{ cloud_name }}"
      when: display_networks
    
    - name: Show openstack subnets
      debug:
        var: openstack_subnets
      when: display_networks
