
- hosts: "*"
  vars:
  gather_facts: False
  tasks:
  - name: hostname
    command: hostname
  - name: debug
    debug:
      var: hostvars
  - name: debug
    debug:
      var: openstack.metadata.logical_name
    when: "openstack is defined and openstack.metadata.logical_name == 'bastion'"
  - name: debug
    debug:
      var: test_var
    when: "'test2' in test_var.split(',')"