- hosts: localhost
  gather_facts: False

  vars:
    otvl_os_server:
      extra_data:
        vm_state: arror
      msg: "ERR0r!!!"

  tasks:
  - name: "ah"
    debug:
      msg: "Ah"
    when:
    - '(otvl_os_server.extra_data.vm_state is defined and otvl_os_server.extra_data.vm_state|regex_search("error", ignorecase=True)) or (otvl_os_server.msg is defined and otvl_os_server.msg|regex_search("error", ignorecase=True))'
