---
all:
  hosts:
  children:
    iaas_configure:
      hosts:
        kslba:
        ksldk:
    docker_builder_group:
      hosts:
        ksldk:
    docker_runner_group:
      hosts:
        ksldk:
    nfs_client_group:
      hosts:
        ksldk:
    nfs_server_group:
      hosts:
        kslba:
    tor_group:
      hosts:
        ksldk:
    wc_build_group:
      hosts:
        ksldk:
    wc_run_group:
      hosts:
        ksldk:

###