version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
auth:
  htpasswd:
    realm: otvl-dkr
    path: /etc/otvl-dkr-passwd
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3