---

ansible_user: guest
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_private_key_file: ~/.ssh/id_rsa
ansible_ssh_extra_args: -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

infra:
  servers:
    bastion:
      name: kslba
      ips:
        admin: 172.23.0.2
        appli: 172.24.0.2
    otfe:
      name: dxotfe
      ips:
        admin: 172.23.0.30
        appli: 172.24.0.30
    otbe:
      name: dxotbe
      ips:
        admin: 172.23.0.40
        appli: 172.24.0.40
  networks:
    external:
      name: Ext-Net
    admin:
      name: admin-net
    appli:
      name: appli-net
  dns:
    resolv_conf_content: |
      # created by otvl_network_configurator
      nameserver 192.168.122.1

otvl:
  debug: false
  config_paths:
    sbin: /srv/sbin
    data: /srv/data
    backup: /srv/backup
    delivery: /srv/delivery
    pkg: /srv/pkg
  config_vars:
    admin_user: guest
  apache:
    www: /srv/www
    sites:
      otfe:
        ssl_sni:
          apache_modules: ['ssl', 'proxy', 'proxy_http']
          template: apache/conf/ssl_sni.conf
          site_items:
          - name: site1
            template: apache/conf/otvl_web_front_end.inc
            vars:
              server_name: site1.dxotfe
              backend_server: dxotbe
              web_port: "9981"
              api_port: "9991"
              auto_pki_path: override/apache/auto_pki
          - name: site2
            template: apache/conf/otvl_web_front_end.inc
            vars:
              server_name: site2.dxotfe
              backend_server: dxotbe
              web_port: "9982"
              api_port: "9992"
              auto_pki_path: override/apache/auto_pki
      otbe:
        private_ports_farm:
          apache_modules: []
          template: apache/conf/private_ports_farm.conf
          site_items:
          - name: site1
            template: apache/conf/otvl_web_back_end.inc
            vars:
              server_name: site1.dxotfe
              web_port: "9981"
              api_port: "9991"
          - name: site2
            template: apache/conf/otvl_web_back_end.inc
            vars:
              server_name: site2.dxotfe
              web_port: "9982"
              api_port: "9992"
  otvl_web:
    static_site_archive_file: "/srv/export_dir/guest/otvl_web_vuejs-1.0.dev002.tgz"
    virtualenv_archive_file: "/srv/export_dir/guest/otvl_web_server_venv-1.0.dev002.tgz"
    sites:
      otbe:
        site_items:
        - name: site1
          api_port: "9991"
          git:
            repo: "ssh://guest@dxoffice/data/E4/projets/misc/entfram/d9devops/git_repos/pri/otvl_web.git"
            version: "pri_dev_00001"
            content_path: "server/data/test_site1"
          assets_path: "/home/guest/git/otvl_web/server/data/test_site1/assets"
        - name: site2
          api_port: "9992"
          git:
            repo: "ssh://guest@dxoffice/data/E4/projets/misc/entfram/d9devops/git_repos/pri/otvl_web.git"
            version: "pri_dev_00001"
            content_path: "server/data/test_site2"
          assets_path: "/home/guest/git/otvl_web/server/data/test_site2/assets"

###