---

ansible_user: guest
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_private_key_file: ~/.ssh/id_rsa
ansible_ssh_extra_args: -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

infra:
  servers:
    bastion:
      name: kslba
      ips:
        admin: 172.23.0.2
        appli: 172.24.0.2
    otfe:
      name: dxotfe
      ips:
        admin: 172.23.0.30
        appli: 172.24.0.30
  networks:
    external:
      name: Ext-Net
    admin:
      name: admin-net
    appli:
      name: appli-net
  dns:
    resolv_conf_content: |
      # created by otvl_network_configurator
      nameserver 192.168.122.1

otvl:
  config_paths:
    sbin: /srv/sbin
    data: /srv/data
    backup: /srv/backup
    delivery: /srv/delivery
    pkg: /srv/pkg
  config_vars:
    admin_user: guest
  apache:
    sites:
      otfe:
        ssl_sni:
          template: apache/conf/ssl_sni.conf
          site_items:
          - name: site1
            template: otvl_web_front_end.inc
            vars:
              server_name: site1.dxpydk
              web_port: "9981"
              api_port: "9991"
          - name: site2
            template: otvl_web_front_end.inc
            vars:
              server_name: site2.dxpydk
              web_port: "9982"
              api_port: "9992"

###