---
all:
  hosts:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: guest
    infra:
      dns:
        resolv_conf_content: |
          # created by otvl_network_configurator
          nameserver 192.168.122.1
    otvl:
      config_paths:
        sbin: /srv/sbin
        data: /srv/data
        backup: /srv/backup
        delivery: /srv/delivery
        pkg: /srv/pkg
      config_vars:
        admin_user: guest
        admin_key: sample_admin_key
      apache:
        www: /srv/www
        test_notify_restart: false
        test_htpasswd_create: true
        test_htpasswd_users:
          testuser1: password1
          testuser2: password2
        virtual_hosts:
          ksgits:
            otvl_vh:
              server_name: ksgits
              ip: ansible_all_ipv4_addresses[0]
              port: 9090
              aliases:
                - name: public
                  directory: /srv/www/public
                - name: private
                  directory: /srv/www/priv
            otvl_backend_vh:
              server_name: ksgits
              ip: ansible_all_ipv4_addresses[0]
              port: 80

  children:
    bastion_controlled_group:
      hosts:
        ksdkb:
        ksgits:
      vars:
      children:
        bastion_group:
          hosts:
            ksbas:
          vars:
    docker_build_group:
      hosts:
        ksdkb:
      vars:
    git_service_group:
      hosts:
        ksgits:
      vars:
###