log:
  level: "{{ combined_otvl.traefik.log_level | default('INFO') }}"

api:
  insecure: false

providers:
  file:
    directory: /traefik/dynamic_conf
    watch: true

entryPoints:
  web:
    address: ":{{ combined_otvl.traefik.ctr.http_port | default('80') }}"
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: ":{{ combined_otvl.traefik.ctr.https_port | default('443') }}"
    http:
      tls:
        certResolver: le-resolver

certificatesResolvers:
  le-resolver:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      storage: /traefik/acme.json
      httpChallenge:
        entryPoint: web