---
# config_site tasks file for otvl_service/otvl_web_v5/deploy/host

- name: config_site display the site {{ current_site_item.name }} information
  debug:
    msg: "site item is {{ current_site_item }}"
  when: combined_otvl.debug

- name: Create a directory for volume of the site {{ current_site_item.name }} Pod API
  file:
    path: /srv/data/{{ current_site_item.name }}-api-pv
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Create a directory for volume of the site {{ current_site_item.name }} Pod App
  file:
    path: /srv/data/{{ current_site_item.name }}-app-pv
    state: directory
    owner: root
    group: root
    mode: 0700
