synchronize:
  period: 60
  actions:
    - type: git
      gitSpec:
        repoUrl: "{{ current_site_item.git.otvl_site.repo }}"
        branch: "{{ current_site_item.git.otvl_site.version }}"
        clonePath: "/data/git"
