---
# main tasks file for otvl_service/otvl_web_v2/docker_run

- name: Install git for otvl_web_v2/docker_build
  ansible.builtin.apt:
    pkg: git

- name: Docker login for docker-compose services to find the registry
  block:
    - command:
        cmd: "docker login {{ combined_otvl.otvl_web_v2.docker_registry }} -u {{ combined_otvl.otvl_web_v2.docker_login }} --password-stdin"
        stdin: "{{ combined_otvl.otvl_web_v2.docker_password }}"
      register: docker_login
    - debug: var=docker_login.cmd
    - debug: var=docker_login.stderr_lines
    - debug: var=docker_login.stdout_lines

- name: Loop over sites for running stacks
  include_tasks: run_site.yml
  loop: "{{ combined_otvl.otvl_web_v2.sites[otvl_logical_name].site_items }}"
  loop_control:
    loop_var: current_site_item
  when: "(current_site_item.skip_deployment | default(false)) != true"

###