---
# main tasks file for otvl_cloud/init

- name: combine default with actual infra data
  set_fact:
    combined_infra: "{{ default_infra | combine(infra, recursive=True) }}"

- name: Loop over internal networks
  include_tasks: create_network.yml
  loop: "{{ combined_infra.networks|dict2items }}"
  when: item.key != "external"

- name: Create a security group {{ combined_infra.security_groups.cloud_init_access }} for cloud init access
  os_security_group:
    cloud: "{{ cloud_name }}"
    state: present
    name: "{{ combined_infra.security_groups.cloud_init_access }}"

- name: Create a security group rule ICMP on {{ combined_infra.security_groups.cloud_init_access }} for cloud init access
  os_security_group_rule:
    cloud: "{{ cloud_name }}"
    security_group: "{{ combined_infra.security_groups.cloud_init_access }}"
    protocol: icmp
    remote_ip_prefix: 0.0.0.0/0

- name: Create a security group rule SSH on {{ combined_infra.security_groups.cloud_init_access }} for cloud init access
  os_security_group_rule:
    cloud: "{{ cloud_name }}"
    security_group: "{{ combined_infra.security_groups.cloud_init_access }}"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0

- name: Create a security group rule egress v4 on {{ combined_infra.security_groups.cloud_init_access }} for cloud init access
  os_security_group_rule:
    cloud: "{{ cloud_name }}"
    security_group: "{{ combined_infra.security_groups.cloud_init_access }}"
    direction: egress
    remote_ip_prefix: 0.0.0.0/0
  when: combined_infra.security_groups.require_open_egress

- name: Create a security group rule egress v6 on {{ combined_infra.security_groups.cloud_init_access }} for cloud init access
  os_security_group_rule:
    cloud: "{{ cloud_name }}"
    security_group: "{{ combined_infra.security_groups.cloud_init_access }}"
    direction: egress
    ethertype: IPv6
    remote_ip_prefix: ::/0
  when: combined_infra.security_groups.require_open_egress

- name: Create a security group {{ combined_infra.security_groups.admin_traffic }} for admin internal traffic
  os_security_group:
    cloud: "{{ cloud_name }}"
    state: present
    name: "{{ combined_infra.security_groups.admin_traffic }}"
  register:
    otvl_os_security_group_admin

- name: Create a security group {{ combined_infra.security_groups.appli_traffic }} for application internal traffic
  os_security_group:
    cloud: "{{ cloud_name }}"
    state: present
    name: "{{ combined_infra.security_groups.appli_traffic }}"
  when: otvl_os_security_group_admin.changed

- name: Create a security group rule ICMP on {{ combined_infra.security_groups.appli_traffic }} for application internal traffic
  os_security_group_rule:
    cloud: "{{ cloud_name }}"
    security_group: "{{ combined_infra.security_groups.appli_traffic }}"
    protocol: icmp
    remote_ip_prefix: "{{ combined_infra.networks.appli.cidr }}"
  when: otvl_os_security_group_admin.changed

- name: Create a security group rule ingress v4 on {{ combined_infra.security_groups.appli_traffic }} for application internal traffic
  os_security_group_rule:
    cloud: "{{ cloud_name }}"
    security_group: "{{ combined_infra.security_groups.appli_traffic }}"
    remote_ip_prefix: "{{ combined_infra.networks.appli.cidr }}"
  when: otvl_os_security_group_admin.changed

- name: Loop over servers
  include_tasks: create_server.yml
  loop: "{{ combined_infra.servers|dict2items }}"

###