---
# included tasks file for otvl_cloud/init

- openstack.cloud.server_info:
    cloud: "{{ cloud_name }}"
    filters:
      metadata:
        hostname: "{{ item.value.name }}"
  register: os_server_info

- name: set security groups for bastion server {{ item.value.name }}
  set_fact:
    otvl_server_security_groups:
    - "{{ combined_infra.security_groups.bastion_access }}"
    - "{{ combined_infra.security_groups.cloud_init_access }}"
  when: "'bastion_group' in item.value.groups"

- name: set security groups for non bastion server {{ item.value.name }}
  set_fact:
    otvl_server_security_groups:
    - "{{ combined_infra.security_groups.cloud_init_access }}"
    - "{{ combined_infra.security_groups.ext_access }}"
  when: "'bastion_group' not in item.value.groups"

- openstack.cloud.server_info:
    cloud: "{{ cloud_name }}"
    filters:
      metadata:
        hostname: "{{ item.value.name }}"
  register: os_server_info

- name: "Set public port info for the server"
  set_fact:
    otvl_pp_id: "{{ var_port[0].id }}"
  loop: "{{ otvl_os_ports_info.openstack_ports | subelements('fixed_ips') }}"
  loop_control:
    label: "{{ var_port[0].id }}"
    loop_var: var_port
  when: "var_port[1].ip_address == os_server_info.openstack_servers[0].public_v4"

- name: Create a security group rule SSH on {{ combined_infra.security_groups.bastion_access }} for bastion access
  os_security_group_rule:
    cloud: "{{ cloud_name }}"
    security_group: "{{ combined_infra.security_groups.bastion_access }}"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: "{{ os_server_info.openstack_servers[0].public_v4 }}/0"
  when: "'bastion_group' in item.value.groups"
  
- name: "Update security for public port"
  shell: "{{ combined_infra.otvl_configure.openstack_path }}/openstack --os-cloud {{ cloud_name }} port set {{ otvl_pp_id }} --security-group {{ combined_infra.security_groups.cloud_init_access if 'bastion_group' in item.value.groups else combined_infra.security_groups.bastion_access }}"

###