apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    logs:
      general:
        level: DEBUG
    ports:
      websecure:
        http:
          tls:
            certResolver: leresolver

    certResolvers:
      leresolver:
        caServer: https://acme-v02.api.letsencrypt.org/directory
        storage: /data/acme.json
        tlsChallenge: false
        httpChallenge:
          entryPoint: web
