apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    persistence:
      enabled: true
      existingClaim: traefik-acme-pvc
    logs:
      general:
        level: DEBUG
    ports:
      websecure:
        tls:
          certResolver: leresolver
    certResolvers:
      leresolver:
        caServer: https://acme-staging-v02.api.letsencrypt.org/directory
        storage: /data/acme.json
        tlsChallenge: false
        httpChallenge:
          entryPoint: web
    deployment:
      initContainers:
        - name: volume-permissions
          image: busybox:latest
          command: ["sh", "-c", "touch /data/acme.json; chmod -v 600 /data/acme.json"]
          volumeMounts:
            - mountPath: /data
              name: data
