apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    persistence:
      enabled: true
    logs:
      general:
        level: DEBUG
    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          certResolver: leresolver
    certResolvers:
      leresolver:
        caServer: https://acme-staging-v02.api.letsencrypt.org/directory
        storage: /data/acme.json
        tlsChallenge: false
        httpChallenge:
          entryPoint: web
