apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    persistence:
      enabled: true
    logs:
      general:
        level: INFO
      access:
        enabled: true
        fields:
          headers:
            defaultMode: keep
            names:
              User-Agent: drop
              Authorization: drop
              Content-Type: drop
              X-Forwarded-Proto: keep
              X-Forwarded-For: keep
              Host: keep
              Docker-Distribution-API-Version: keep
    
    ports:
      web:
        redirectTo:
          port: websecure
      websecure:
        tls:
          certResolver: leresolver
    certResolvers:
      leresolver:
        storage: /data/acme.json
        tlsChallenge: false
        httpChallenge:
          entryPoint: web
