---
# main tasks file for otvl_service/otvl_web_v2/docker_build

- name: Install git for otvl_web_v2/docker_build
  ansible.builtin.apt:
    pkg: git

- name: Loop over sites for building images
  include_tasks: build_site.yml
  loop: "{{ combined_otvl.otvl_web_v2.sites[otvl_logical_name].site_items }}"
  loop_control:
    loop_var: current_site_item
  when: "(current_site_item.skip_build | default(false)) != true"

###