apiVersion: v1
kind: ConfigMap
metadata:
  name: ctr-reg-cmap
data:
  "config.yml": |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3

---
apiVersion: v1
kind: Pod
metadata:
  name: ctr-reg
  labels:
    app.kubernetes.io/name: ctr-reg
spec:
  securityContext:
    runAsUser: {{ combined_otvl.ctr.uid }}
    runAsGroup: {{ combined_otvl.ctr.uid }}
    fsGroup: {{ combined_otvl.ctr.fs_group }}
  containers:
    - name: ctr-reg
      image: registry:2
      ports:
        - containerPort: 5000
      volumeMounts:
        - name: ctr-vol
          mountPath: /var/lib/registry
        - name: ctr-config-vol
          mountPath: /etc/docker/registry

  volumes:
    - name: ctr-vol
      persistentVolumeClaim:
        claimName: ctr-pvc
    - name: ctr-config-vol
      configMap:
        name: ctr-reg-cmap

  restartPolicy: OnFailure

---
apiVersion: v1
kind: Service
metadata:
  name: ctr-reg
spec:
  selector:
    app.kubernetes.io/name: ctr-reg
  ports:
    - name: reg-port
      port: 5000
      protocol: TCP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ctr-router-cmap
data:
  "static-config.yml": |
    log:
      level: INFO
    accessLog:
      format: json
      fields:
        defaultMode: keep
    providers:
      file:
        filename: /traefik/dynamic-conf.yml
        watch: true
    entryPoints:
      web:
        address: ':5000'

  "dynamic-conf.yml": |
    http:
      routers:
        to-app:
          rule: "PathPrefix(`/`)"
          middlewares:
            - basic-auth
            - https-header
          service: reg
      middlewares:
        basic-auth:
          basicAuth:
            users:
              - "{{ combined_otvl.ctr.apr_credentials }}"
        https-header:
          headers:
            customRequestHeaders:
              X-Forwarded-Proto: "https"
      services:
        "reg":
          loadBalancer:
            servers:
              - url: "http://ctr-reg:5000"

---
apiVersion: v1
kind: Pod
metadata:
  name: ctr-router
  labels:
    app.kubernetes.io/name: ctr-router
spec:
  securityContext:
    runAsUser: {{ combined_otvl.ctr.uid }}
    runAsGroup: {{ combined_otvl.ctr.uid }}
  containers:
    - name: ctr-router
      image: "{{ combined_otvl.traefik.image }}"
      command: ["/usr/local/bin/traefik"]
      args: ["--configFile=/traefik/static-config.yml"]
      ports:
        - containerPort: 5000
      volumeMounts:
        - name: ctr-config-vol
          mountPath: /traefik
  volumes:
    - name: ctr-config-vol
      configMap:
        name: ctr-router-cmap
  restartPolicy: OnFailure

---
apiVersion: v1
kind: Service
metadata:
  name: ctr-router
spec:
  selector:
    app.kubernetes.io/name: ctr-router
  ports:
    - name: router-port
      port: 5000
      protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ctr-router
spec:
  rules:
    - host: "{{ combined_otvl.ctr.ingress_host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  ctr-router
                port:
                  number: 5000
