---
# main tasks file for otvl_bastion/bastion
- name: combine default with actual otvl config data
  set_fact:
    combined_otvl: "{{ default_otvl | combine(otvl, recursive=True) }}"

- name: Copy ssh admin private key to on the bastion
  copy:
    src: ssh/admin_key
    dest: /home/{{ combined_otvl.config_vars.admin_user }}/.ssh/{{ combined_otvl.config_vars.admin_key }}
    owner: "{{ combined_otvl.config_vars.admin_user }}"
    group: "{{ combined_otvl.config_vars.admin_user }}"
    mode: 0600

- name: Copy ssh admin public key to on the bastion
  copy:
    src: ssh/admin_key.pub
    dest: /home/{{ combined_otvl.config_vars.admin_user }}/.ssh/{{ combined_otvl.config_vars.admin_key }}.pub
    owner: "{{ combined_otvl.config_vars.admin_user }}"
    group: "{{ combined_otvl.config_vars.admin_user }}"
    mode: 0600

###