---
# main tasks file for otvl_service/base_service

- name: Load default otvl (base) variables
  include_vars:
    dir: "{{ role_path }}/../../vars/defaults"

- name: combine default with actual infra config data (base)
  set_fact:
    combined_infra: "{{ default_infra | combine(infra, recursive=True) }}"

- name: combine default with actual otvl config data (base)
  set_fact:
    combined_otvl: "{{ default_otvl | combine(otvl, recursive=True) }}"

- name: set logical name for server {{ inventory_hostname }} (base)
  set_fact:
    otvl_logical_name: "{{ item.key }}"
  when: 'item.value.name == inventory_hostname'
  loop: "{{ combined_infra.servers | dict2items }}"

- name: set configuration data for server {{ inventory_hostname }} => {{ otvl_logical_name }} (base)
  set_fact:
    server_infra: "{{ combined_infra.servers[otvl_logical_name] }}"

- name:
  pause:
    prompt: "Pause is enabled, do you want to continue?"
  when: combined_otvl.pause

- name:
  pause:
    prompt: "Ah ah! you want to deploy in production, do you want to continue?"
  when: combined_otvl.prod

- name: Create otvl root directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ combined_otvl.config_paths.sbin }}"
    - "{{ combined_otvl.config_paths.data }}"
    - "{{ combined_otvl.config_paths.data }}/installation_flags"
    - "{{ combined_otvl.config_paths.backup }}"
    - "{{ combined_otvl.config_paths.delivery }}"
    - "{{ combined_otvl.config_paths.pkg }}"

- name: Install common install and util scripts in sbin
  copy:
    src: "sbin/{{ item }}"
    dest: "{{ combined_otvl.config_paths.sbin }}/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - otvl_apt_subs.sh
    - otvl_sbin_lib.sh

###