---
# otvl_service/base_service/tasks/set_install_status_file.yml
# set install status
# vars:
#   isf_name: install status file name
#   isf_status: install status to be set
#   isf_force: yes/no force setting install status if file already present
# returns set_isf.changed if file created

- name: "Install status {{ isf_name }} created"
  copy:
    dest: "{{ combined_otvl.config_paths.data }}/installation_flags/isf_{{ isf_name }}.txt"
    content: "{{ isf_status }}"
    force: "{{ isf_force }}"
  register: set_isf

###