---
# default otvl variable for otvl_ansible playbooks and roles

default_otvl:
  debug: false
  config_paths:
    sbin: /otvl/sbin
    data: /otvl/data
    backup: /otvl/backup
    delivery: /otvl/delivery
    pkg: /otvl/pkg
  config_vars:
    admin_user: otvl_admin_user
    admin_key: otvl_admin_key
    devops_user: devops
    devops_key: id_rsa_devops
    otvl_ansible_git_repo: https://github.com/t-beigbeder/otvl_ansible
    otvl_ansible_git_version: master
    otvl_anprin_local_git_repo_tgz: /path/to/bare/otvl_anprin.git.tar.gz
  apache:
    www: /otvl/www
    user: www-data
    group: www-data
    dis_sites:
    - 000-default
    test_notify_restart: false
    test_htpasswd_create: false
    test_htpasswd_path: apache/htpasswd
    test_htpasswd_users: {}
    sites: {}

  otvl_web:
    static_site_archive_file: "/path/to/otvl_web_vuejs-1.0.x.tgz"
    virtualenv_archive_file: "/path/to/otvl_web_server_venv-1.0.y.tgz"
    sites: {}

  git_service:
    project_root: git
    project_artifacts_root: artifacts
    user: www-data
    group: www-data
    max_backup: 35
    apache_modules:
    - cgid
    - alias
    - env
    apache_location: git
    # redefine to authenticate read access too, useful with tool such as egit
    apache_location_rw: git
    apache_artifacts_location: artifacts
    apache_artifacts_folders: []

###