---
# install_site_apache_front_end tasks file for otvl_service/otvl_web/front_end

- name: display the site information
  debug:
    msg: "site is {{ current_site.key }}: {{ current_site.value }}"
  when: combined_otvl.debug

- name: Loop over sites items for apache installation (otvl_service/front_end)
  include_tasks: install_site_apache_front_end_item.yml
  loop: "{{ current_site.value.site_items }}"
  loop_control:
    loop_var: current_site_item

###