---
# install_site_apache_front_end_item tasks file for otvl_service/otvl_web/front_end

- name: display the site item information
  debug:
    msg: "site item is {{ current_site_item }}"
  when: combined_otvl.debug

- name: Check letsencrypt certificate for site {{ current_site_item.template }}
  stat:
    path: "/etc/letsencrypt/archive/{{ current_site_item.vars.server_name }}"
  register: letsencrypt_archive_dir

- name: Install the site item configuration file /etc/apache2/otvl_conf/{{ current_site_item.name }}.inc
  template:
    src: "{{ current_site_item.template }}"
    dest: "/etc/apache2/otvl_conf/{{ current_site_item.name }}.inc"
    owner: root
    group: root
    mode: 0644
  notify: Restart the apache service

###