---
# install_site_front_end_item tasks file for otvl_service/otvl_web/front_end

- name: display the site item information
  debug:
    msg: "site item is {{ current_site_item }}"
  when: combined_otvl.debug

- name: Install the site item configuration file {{ current_site_item.template }}
  template:
    src: "{{ current_site_item.template }}"
    dest: "/etc/apache2/otvl_conf/{{ current_site_item.name }}.inc"
    owner: root
    group: root
    mode: 0644
  notify: Restart the apache service

- name: Create letsencrypt certificates directory /etc/letsencrypt/live/
  file:
    path: "/etc/letsencrypt/live/"
    state: directory
    owner: root
    group: root
    mode: 0700
  when: "'cert_bot' in current_site_item.vars and current_site_item.vars.cert_bot"

- name: Create letsencrypt certificates directory for site {{ current_site_item.name }}
  file:
    path: "/etc/letsencrypt/live/{{ current_site_item.vars.server_name }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: "'cert_bot' in current_site_item.vars and current_site_item.vars.cert_bot"

- name: Copy self signed certificate to letsencrypt certificates directory for site {{ current_site_item.name }}
  copy:
    src: "/etc/ssl/certs/{{ current_site_item.vars.server_name }}.crt"
    remote_src: yes
    dest: "/etc/letsencrypt/live/{{ current_site_item.vars.server_name }}/fullchain.pem"
    force: no
  when: "'cert_bot' in current_site_item.vars and current_site_item.vars.cert_bot"

- name: Copy self signed key to letsencrypt certificates directory for site {{ current_site_item.name }}
  copy:
    src: "/etc/ssl/private/{{ current_site_item.vars.server_name }}.key"
    remote_src: yes
    dest: "/etc/letsencrypt/live/{{ current_site_item.vars.server_name }}/privkey.pem"
    force: no
  when: "'cert_bot' in current_site_item.vars and current_site_item.vars.cert_bot"

###