---
# main tasks file for otvl_service/otvl_web/front_end
- name: debug
  debug:
    var: combined_otvl
  when: combined_otvl.debug

- name: Install virtualenv for otvl_web_service
  command: env
  args:
    creates: /usr/bin/virtualenv
    warn: false
  environment:
    LC_ALL: C
    DEBIAN_FRONTEND: noninteractive

###