---
# install_site_vuejs_back_end_item tasks file for otvl_service/otvl_web/back_end

- name: install_site_vuejs_back_end_item display the site item information
  debug:
    msg: "site item is {{ current_site_item }}"
  when: combined_otvl.debug

- name: Flag absent to continue
  include_tasks: "{{ role_path }}/../../base_service/tasks/get_flag_for.yml"
  vars:
    flag_type: static_site_archive_file
    flag_item: "{{ current_site_item.name }}"

- name: Create and configure vuejs static site directory for {{ current_site_item.name }}
  block:
  - name: Create vuejs static site directory for {{ current_site_item.name }}
    file:
      path: "{{ combined_otvl.apache.www }}/{{ current_site_item.name }}"
      state: directory
      mode: 0755

  - name: Clean-up vuejs static site web directory for {{ current_site_item.name }}
    file:
      path: "{{ combined_otvl.apache.www }}/{{ current_site_item.name }}/web"
      state: absent

  - name: Copy vuejs static site for {{ current_site_item.name }}
    copy:
      src: "{{ combined_otvl.config_paths.pkg }}/otvl_web_vuejs/"
      remote_src: yes
      dest: "{{ combined_otvl.apache.www }}/{{ current_site_item.name }}/web"
      force: no
      owner: root
      group: root
      mode: u+rwX,go+rX

  - name: Restore {{ combined_otvl.apache.www }}/{{ current_site_item.name }}/web/index.html.ori
    command: "mv {{ combined_otvl.apache.www }}/{{ current_site_item.name }}/web/index.html.ori {{ combined_otvl.apache.www }}/{{ current_site_item.name }}/web/index.html"

  - name: Remove assets symlink from {{ combined_otvl.apache.www }}/{{ current_site_item.name }}/web
    file:
      path: "{{ combined_otvl.apache.www }}/{{ current_site_item.name }}/web/assets"
      state: absent

  - name: Configure default_web_server_url {{ combined_otvl.apache.www }}/{{ current_site_item.name }}/web/index.html
    replace:
      path: "{{ combined_otvl.apache.www }}/{{ current_site_item.name }}/web/index.html"
      regexp: '=default_web_server_url'
      replace: '=https://{{ current_site_item.vars.server_name }}'

  - name: Configure default_api_server_url {{ combined_otvl.apache.www }}/{{ current_site_item.name }}/web/index.html
    replace:
      path: "{{ combined_otvl.apache.www }}/{{ current_site_item.name }}/web/index.html"
      regexp: '=default_api_server_url'
      replace: "=https://{{ current_site_item.vars.server_name }}/api"

  - name: Configure otvl_web_home_title {{ combined_otvl.apache.www }}/{{ current_site_item.name }}/web/index.html
    replace:
      path: "{{ combined_otvl.apache.www }}/{{ current_site_item.name }}/web/index.html"
      regexp: "<title>otvl_web_home_title"
      replace: "<title>{{ current_site_item.vars.home_title }}"

  - name: Template {{ combined_otvl.apache.www }}/{{ current_site_item.name }}/web/robots.txt
    template:
      src: "apache/web/robots.txt"
      dest: "{{ combined_otvl.apache.www }}/{{ current_site_item.name }}/web/robots.txt"
      owner: root
      group: root
      mode: 0644

  - name: Flag present
    include_tasks: "{{ role_path }}/../../base_service/tasks/set_flag_for.yml"
    vars:
      flag_type: static_site_archive_file
      flag_item: "{{ current_site_item.name }}"

  - name: no op for notifying apache
    debug:
      msg: no op for notifying apache
    notify: Restart the apache service

  rescue:
  - name: rescue for Create and configure vuejs static site directory for {{ current_site_item.name }}
    debug:
      msg: Create and configure vuejs static site directory for {{ current_site_item.name }}
    when: combined_otvl.debug

  when: "flag_file_state.failed"

###