---
# main tasks file for otvl_service/otvl_ctr/host

- name: Create the docker registry configuration directory
  file:
    path: "{{ combined_otvl.config_paths.data }}/otvl_ctr"
    state: directory
    mode: 0755

- name: Create the docker registry directory
  file:
    path: "{{ combined_otvl.config_paths.data }}/otvl_ctr/docker_registry"
    state: directory
    owner: "{{ combined_otvl.ctr.uid }}"
    group: "{{ combined_otvl.ctr.uid }}"
    mode: 0755

###