---
# deploy_site tasks file for otvl_service/otvl_web_v4/deploy

- name: deploy_site display the site {{ current_site_item.name }} information
  debug:
    msg: "site item is {{ current_site_item }}"
  when: combined_otvl.debug

- name: Kubectl apply site {{ current_site_item.name }} pods deployment
  block:
    - command:
        cmd: "kubectl apply  -"
        stdin: "{{ lookup('template', 'otvl_web_deploy.yaml') }}"
      register: kapply
    - debug: var=kapply.cmd
    - debug: var=kapply.stderr_lines
    - debug: var=kapply.stdout_lines
