---
# main tasks file for otvl_service/docker/base_docker

- name: Install docker pre-requisites
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - gpg
      - software-properties-common
    state: present
    update_cache: yes
    install_recommends: no

- name: Install docker apt key
  ansible.builtin.apt_key:
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker repository into sources list
  ansible.builtin.apt_repository:
    repo: deb http://download.docker.com/linux/debian buster stable
    state: present

- name: Install docker run-time and CLI
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
    install_recommends: no

- name: "Enable admin_user {{ combined_otvl.config_vars.admin_user }} as docker user"
  ansible.builtin.user:
    name: "{{ combined_otvl.config_vars.admin_user }}"
    groups: docker
    append: yes

- name: Download and install /usr/local/bin/docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.28.5/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 755

###