- hosts: "*"
  gather_facts: False
  tasks:
  - name: Load default variables
    include_vars:
      dir: vars/defaults

- hosts: git_service_group
  gather_facts: False
  become: yes
  roles:
  - otvl_service/git_service
  tags:
  - otvl_git_service
