- hosts: "*"
  gather_facts: False
  tasks:
  - name: Load default variables
    include_vars:
      dir: vars/defaults
  tags: always

- hosts: bastion_controlled_group
  gather_facts: False
  become: yes
  roles:
  - otvl_cloud/configure
  tags:
  - otvl_iaas_configure

- hosts: bastion_controlled_group
  gather_facts: False
  become: yes
  roles:
  - otvl_bastion/controlled
  tags:
  - otvl_bastion
