- hosts: "*"
  gather_facts: False
  tasks:
  - name: Load default variables
    include_vars:
      dir: vars/defaults
  tags: always

- hosts: otvl_v4_dkr
  gather_facts: False
  become: yes
  roles:
    - otvl_service/traefik
  tags:
    - traefik

- hosts: otvl_v4_dkr
  gather_facts: False
  become: yes
  roles:
    - otvl_service/otvl_dkr
  tags:
    - otvl_v4_dkr

- hosts: otvl_v4_k3s
  gather_facts: False
  become: yes
  roles:
    - otvl_service/k3s
  tags:
    - otvl_v4_k3s

###