- hosts: "*"
  gather_facts: False
  tasks:
  - name: Load default variables
    include_vars:
      dir: vars/defaults
  tags: always

- hosts: iaas_init
  gather_facts: False
  roles:
  - otvl_cloud/filter
  tags:
  - otvl_iaas_init

- hosts: "*"
  tasks:
    - name: Run hostname
      command:
        cmd: hostname