---
# install_site_item tasks file for otvl_service/apache

- name: display the site item information (otvl_service/apache)
  debug:
    msg: "site item is {{ current_site_item }}"
  when: combined_otvl.debug

- name: Install autosigned certificate if configured
  copy:
    src: "{{ current_site_item.vars.auto_pki_path }}/{{ current_site_item.vars.server_name }}.crt"
    dest: "/etc/ssl/certs/{{ current_site_item.vars.server_name }}.crt"
    owner: root
    group: root
    mode: 0644
  when: "'auto_pki_path' in current_site_item.vars"

- name: Install autosigned certificate if configured
  copy:
    src: "{{ current_site_item.vars.auto_pki_path }}/{{ current_site_item.vars.server_name }}.key"
    dest: "/etc/ssl/private/{{ current_site_item.vars.server_name }}.key"
    owner: root
    group: root
    mode: 0600
  when: "'auto_pki_path' in current_site_item.vars"

###