apiVersion: v1
kind: Pod
metadata:
  name: {{ current_site_item.name }}-api
  labels:
    app.kubernetes.io/name: {{ current_site_item.name }}-api
spec:
  containers:
  - name: {{ current_site_item.name }}-api-sync
    image: dkr.otvl.org/cabrisched:0.2.2
    command: ["/bin/sh"]
    args: ["-c", "/entrypoint.sh /usr/local/bin/cabri schedule --pfile /etc/cabri-pfile --sfile /etc/cabri-sfile.yaml --http"]
    ports:
      - containerPort: 3000
        name: {{ current_site_item.name }}-apisp
  restartPolicy: OnFailure

---
apiVersion: v1
kind: Service
metadata:
  name: {{ current_site_item.name }}-api-sync-service
spec:
  selector:
    app.kubernetes.io/name: {{ current_site_item.name }}-api
  ports:
    - name: {{ current_site_item.name }}-apissp
      protocol: TCP
      port: 3000
      targetPort: {{ current_site_item.name }}-apisp

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ current_site_item.name }}-api-sync
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: test2.k3s.otvl.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  {{ current_site_item.name }}-api-sync-service
                port:
                  number: 3000