apiVersion: v1
kind: Pod
metadata:
  name: {{ current_site_item.name }}-api
  labels:
    app.kubernetes.io/name: {{ current_site_item.name }}-api
spec:
  securityContext:
    runAsUser: {{ current_site_item.uid }}
    runAsGroup: {{ current_site_item.uid }}
    fsGroup: {{ current_site_item.fs_group }}
  containers:
  - name: {{ current_site_item.name }}-api-sync
    image: dkr.otvl.org/cabrisched:0.2.2
    command: ["/bin/sh"]
    args: ["-c", "/entrypoint.sh /usr/local/bin/cabri schedule --pfile /etc/cabri-pfile --sfile /etc/cabri-sfile.yaml --http"]
    ports:
      - containerPort: {{ current_site_item.api_port }}
        name: {{ current_site_item.name }}-apisp
    volumeMounts:
      - name: "{{ current_site_item.name }}-api-vol"
        mountPath: /data
  volumes:
    - name: "{{ current_site_item.name }}-api-vol"
      persistentVolumeClaim:
        claimName: "{{ current_site_item.name }}-api-pvc"

  restartPolicy: OnFailure

---
apiVersion: v1
kind: Service
metadata:
  name: {{ current_site_item.name }}-api-sync-service
spec:
  selector:
    app.kubernetes.io/name: {{ current_site_item.name }}-api
  ports:
    - name: {{ current_site_item.name }}-apissp
      protocol: TCP
      port: {{ current_site_item.api_port }}
      targetPort: {{ current_site_item.name }}-apisp

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ current_site_item.name }}-api-sync
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: {{ current_site_item.ingress_host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  {{ current_site_item.name }}-api-sync-service
                port:
                  number: {{ current_site_item.api_port }}